let x = 6;
console.log(x);
console.log(x * x);
console.log(x * x * x);
console.log();
console.log("=====================================================");
let a = 5;
let b = 6;
let c = 7;
let d = 12;
console.log(a + b + c);
console.log(a * b * c);
console.log("=====================================================");
let suma = a + b;
let skirt = b - a;
console.log(suma * skirt);
console.log("=====================================================");
console.log((a + b + c + d) / 4);
console.log("=====================================================");
let sum = 4 + 5;
let skirtumas = 4 - 5;
let sandauga = 4 * 5;
let dalmuo = 4 / 5;
console.log("4 + 5 =" + sum);
console.log("4 - 5 =" + skirtumas);
console.log("4 * 5 =" + sandauga);
console.log("4 / 5 =" + dalmuo);
console.log("=====================================================");
let pveiksmas = -1 + 4 * 6;
let aveiksmas = (35 + 5) % 7;
let tveiksmas = 14 + (-4 * 6) / 12;
let kveiksmas = 2 + (15 / 6) * 1 - (7 % 2);
console.log("-1 + 4 * 6 =", pveiksmas);
console.log("(35 + 5) % 7 =", aveiksmas);
console.log("14 + -4 * 6 / 12 =", tveiksmas);
console.log("2 + 15 / 6 * 1 - 7 % 2 =", kveiksmas);
console.log("=====================================================");
for (let i = 1; i <= 10; i++) {
  let rezultatas = 5 * i;
  console.log("5 * " + i + " = " + rezultatas);
}
console.log("=====================================================");
